### ISSUE TITLE
Warning hex2bin(): Hexadecimal input string must have an even length

### ISSUE THREAD

**Issue by salmantzo** [lekoala/silverstripe-encrypt#3]
I am using PHP 7.4 and using DBEncryptedText field. When the input consists of only numbers I get the below warning:

[Warning] hex2bin(): Hexadecimal input string must have an even length
Line 81 in vendor\lekoala\silverstripe-encrypt\code\EncryptHelper.php

**Comment by lekoala** [comment]
is it possible that you got unencrypted data in your database? that errors makes me think you are trying to decode something that is not an actual hexadecimal string. please check the value of your input and see if that helps

**Comment by salmantzo** [comment]
It only happens when the input is numeric. When I append a string before the input like (=123456) it works fine. I have not used the decrypt method in my code, all I am doing is defining the field as EncryptedText and storing the data in DB upon form submission. No custom code.

**Comment by lekoala** [comment]
ok i've updated the "isHexadecimal" method, you can give it a try. basically what happens is that the value is either hexadecimal or a raw unencrypted value. if somehow your value (maybe numeric input) are seen as hexadecimal it's going to fail.

if you are serious about encryption though, i've moved since then to ciphersweet. i have no code ready for open sourcing yet, but it works much better and allows searching encrypted data

**Comment by salmantzo** [comment]
Much appreciated. I will give it a try and let you know. Thanks

**Comment by lekoala** [comment]
@salmantzo you might be happy to learn that I updated this module to support ciphersweet. It's a major improvement over the previous version. I'm closing this issue :)
